//
// Created by rfleige on 27.01.22.
//

#ifndef PROTOTYPE_MULTIPARAMETERDEPENDENTSTRUCTUREDGRIDND_H
#define PROTOTYPE_MULTIPARAMETERDEPENDENTSTRUCTUREDGRIDND_H


class MultiparameterDependentStructuredGridnD {

};


#endif //PROTOTYPE_MULTIPARAMETERDEPENDENTSTRUCTUREDGRIDND_H
